var app = new Vue({
  el: "#app",
  data: {
    tabledata:[{
      img:'',
      name:'阿瑟东',
      time:'2020:12:35',
      control:'老师好，请问今天的股市市场怎么样'
    },{
      img:'',
      name:'大v',
      time:'2020:12:35',
      control:'最近的定投基金可以购买'
    },{
      img:'',
      name:'都巴哈',
      time:'2020:12:35',
      control:'老师，什么是定投基金',
    },{
      img:'',
      name:'王老师',
      time:'2020:12:35',
      control:'基金定投是定期定额投资基金的简称，是指在固定的时间（如每月8日）以固定的金额（如500元）投资到指定的开放式基金中，类似于银行的零存整取方式。人们平常所说的基金主要是指证券投资基金。',
    },{
      img:'',
      name:'阿尔',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'萨芬',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'撒瑟',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'张颖',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'李老师',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'李素素',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'那可',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'张思',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'张老师',
      time:'2020:12:35',
      control:'',
    },{
      img:'',
      name:'欧陆',
      time:'2020:12:35',
      control:'',
    }]
  },
  created() {
    
  },
  methods: {
  
  }
});
